# Generated by Django 6.0.5 on 2026-09-22 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0007_meditationtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10080)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practice_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
